/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class client_view_utils_ConsoleUtils */

#ifndef _Included_client_view_utils_ConsoleUtils
#define _Included_client_view_utils_ConsoleUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     client_view_utils_ConsoleUtils
 * Method:    init_console
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_client_view_utils_ConsoleUtils_init_1console
  (JNIEnv *, jclass);

/*
 * Class:     client_view_utils_ConsoleUtils
 * Method:    set_raw_mode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_client_view_utils_ConsoleUtils_set_1raw_1mode
  (JNIEnv *, jclass);

/*
 * Class:     client_view_utils_ConsoleUtils
 * Method:    get_console_width
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_client_view_utils_ConsoleUtils_get_1console_1width
  (JNIEnv *, jclass);

/*
 * Class:     client_view_utils_ConsoleUtils
 * Method:    get_console_height
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_client_view_utils_ConsoleUtils_get_1console_1height
  (JNIEnv *, jclass);

/*
 * Class:     client_view_utils_ConsoleUtils
 * Method:    get_cursor_column
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_client_view_utils_ConsoleUtils_get_1cursor_1column
  (JNIEnv *, jclass);

/*
 * Class:     client_view_utils_ConsoleUtils
 * Method:    get_cursor_row
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_client_view_utils_ConsoleUtils_get_1cursor_1row
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
