/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConsoleUtils */

#ifndef _Included_ConsoleUtils
#define _Included_ConsoleUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ConsoleUtils
 * Method:    init_console
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ConsoleUtils_init_1console
  (JNIEnv *, jclass);

/*
 * Class:     ConsoleUtils
 * Method:    set_raw_mode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ConsoleUtils_set_1raw_1mode
  (JNIEnv *, jclass);

/*
 * Class:     ConsoleUtils
 * Method:    get_console_width
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ConsoleUtils_get_1console_1width
  (JNIEnv *, jclass);

/*
 * Class:     ConsoleUtils
 * Method:    get_console_height
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ConsoleUtils_get_1console_1height
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
